clean: 
	-make -i -C Examples clean
	rm -rf Examples/CMakeFiles
	rm -f Examples/CMakeCache.txt
	rm -f Examples/Makefile
	rm -f Examples/cmake_install.cmake
	-make -i -C AugmSSL clean
	rm -rf AugmSSL/CMakeFiles
	rm -f AugmSSL/CMakeCache.txt
	rm -f AugmSSL/Makefile
	rm -f AugmSSL/cmake_install.cmake
	-make -i -C proto clean
	rm -rf proto/CMakeFiles
	rm -f proto/CMakeCache.txt
	rm -f proto/Makefile
	rm -f proto/cmake_install.cmake

